on:
  workflow_dispatch:
  push:
    branches: [main]

name: Publish Server Image

jobs:
  app-publish:
    name: Publish server image to GitHub Container Registry 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push application image
        run: make app-publish
        env: 
          PLATFORM: linux/amd64,linux/arm64